### ISSUE TITLE
Baud Rate Setting

### ISSUE THREAD

**Issue by shengjiatsai** [rcassani/OpenBCI-Toolkit-LabVIEW#3]
Hello
The default baud rate of openbci_new_cnx is 115200, should I change it to 9600 or keep it as default?

http://docs.openbci.com/Tutorials/11-OpenBCI_on_Windows?fbclid=IwAR1PYMRo2GDxz1jNKBmZqhAmO4SdCDrXIWq0nN-iGk10Li2QgZ3qvu4LFNo

**Comment by rcassani** [comment]
This does not represent a problem
